package mx.infotec.eapoyo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApoyoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApoyoAllPropertiesEquals(Apoyo expected, Apoyo actual) {
        assertApoyoAutoGeneratedPropertiesEquals(expected, actual);
        assertApoyoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApoyoAllUpdatablePropertiesEquals(Apoyo expected, Apoyo actual) {
        assertApoyoUpdatableFieldsEquals(expected, actual);
        assertApoyoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApoyoAutoGeneratedPropertiesEquals(Apoyo expected, Apoyo actual) {
        assertThat(actual)
            .as("Verify Apoyo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApoyoUpdatableFieldsEquals(Apoyo expected, Apoyo actual) {
        assertThat(actual)
            .as("Verify Apoyo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDesc()).as("check desc").isEqualTo(expected.getDesc()))
            .satisfies(a -> assertThat(a.getPrerrequisitos()).as("check prerrequisitos").isEqualTo(expected.getPrerrequisitos()))
            .satisfies(a -> assertThat(a.getKeywords()).as("check keywords").isEqualTo(expected.getKeywords()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApoyoUpdatableRelationshipsEquals(Apoyo expected, Apoyo actual) {
        // empty method
    }
}
