package mx.infotec.eapoyo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolicitudAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudAllPropertiesEquals(Solicitud expected, Solicitud actual) {
        assertSolicitudAutoGeneratedPropertiesEquals(expected, actual);
        assertSolicitudAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudAllUpdatablePropertiesEquals(Solicitud expected, Solicitud actual) {
        assertSolicitudUpdatableFieldsEquals(expected, actual);
        assertSolicitudUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudAutoGeneratedPropertiesEquals(Solicitud expected, Solicitud actual) {
        assertThat(actual)
            .as("Verify Solicitud auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudUpdatableFieldsEquals(Solicitud expected, Solicitud actual) {
        assertThat(actual)
            .as("Verify Solicitud relevant properties")
            .satisfies(a -> assertThat(a.getCurp()).as("check curp").isEqualTo(expected.getCurp()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getPrimerApellido()).as("check primerApellido").isEqualTo(expected.getPrimerApellido()))
            .satisfies(a -> assertThat(a.getSegundoApellido()).as("check segundoApellido").isEqualTo(expected.getSegundoApellido()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()))
            .satisfies(a -> assertThat(a.getDesc()).as("check desc").isEqualTo(expected.getDesc()))
            .satisfies(a -> assertThat(a.getKeywords()).as("check keywords").isEqualTo(expected.getKeywords()))
            .satisfies(a -> assertThat(a.getIneUrl()).as("check ineUrl").isEqualTo(expected.getIneUrl()))
            .satisfies(a -> assertThat(a.getCvUrl()).as("check cvUrl").isEqualTo(expected.getCvUrl()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudUpdatableRelationshipsEquals(Solicitud expected, Solicitud actual) {
        assertThat(actual)
            .as("Verify Solicitud relationships")
            .satisfies(a -> assertThat(a.getApoyo()).as("check apoyo").isEqualTo(expected.getApoyo()));
    }
}
